version: '3'
services:
  app:
    container_name: health-serve-bot
    image: heath-serve-bot:aih
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always